### ISSUE TITLE
Weight file

### ISSUE THREAD

**Issue by Krasner** [hazmicokro/Classification-of-Diabetic-Retinopathy-Disease-in-the-Eyes-Using-EfficientNet-B7-Model#1]
Hi,

Do you have a weight file you can share for the optimized network? I would like to validate these results on my data.

Thanks!

**Comment by hazmicokro** [comment]
> Hi,
> 
> Do you have a weight file you can share for the optimized network? I would like to validate these results on my data.
> 
> Thanks!

Yeah, you can access the saved model that I have made at the following link: https://intip.in/savedmodeldiabeticretinopathy
